language: python

python:
    - 3.7

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false


env:
    global:
        - TOXENV=''
        - TOXARGS=''
        - TOXPOSARGS=''

matrix:

    include:
        # do the actual tests.
        # Do a test in Python 3.7
        - env: TOXENV='coverage' TOX_ARGS=''

        # Check accelerated math version too
          env: SETUP_CMD='test --coverage' PIP_DEPENDENCIES='numexpr'

        # Check for Sphinx doc build errors
        - env: TOXENV='build_docs' TOX_ARGS=''

        # Try Astropy development version
        - env: TOXENV='py37-astrodev-test'
        - python: 3.7
          env: SETUP_CMD='test' ASTROPY_VERSION=development

        # Try Astropy & numpy minimum supported versions,
        # and older Python versions
        - env: TOXENV='py35-numpy113-test'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - pip install tox tox-conda
    - pip install codecov

script:
   - conda info
   - $TOX_CMD $TOX_ARGS

after_success:
   - codecov

notifications:
  email:
    - mperrin@stsci.edu
