[build-system]
requires = ["setuptools >= 38.0.0",
            "setuptools_scm[toml]>=3.4.3",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = "poppy/version.py"
